os: linux
dist: bionic

install:
  - wget -O /tmp/syft.deb https://github.com/anchore/syft/releases/download/v0.58.0/syft_0.58.0_linux_${ARCH}.deb
  - sudo apt install -y /tmp/syft.deb

before_script: 
  - mkdir -p data/${DIST}
  - travis_wait 30 sudo syft packages / -o template -t syft-csv.template --file data/${DIST}/${ARCH}_packages.csv

script: 
  - sudo rm -f travis_wait*
  - sudo chown -R travis:travis data
  - .travis/git-push.sh

jobs:
  include:
    - stage: Collect amd64 package data
      env: ARCH=amd64 DIST=bionic
      arch: amd64
    - stage: Collect ppc64le package data
      env: ARCH=ppc64le DIST=bionic
      arch: ppc64le
    - stage: Compare package data
      env: BASE=amd64 NEW=ppc64le DIST=bionic
      language: python
      before_install: git pull
      install: pip3 install pandas
      before_script: python3 main.py -b data/${DIST}/${BASE}_packages.csv -n data/${DIST}/${NEW}_packages.csv -o data/${DIST}
      arch: amd64

